### ISSUE TITLE
Is the book already available?

### ISSUE THREAD

**Issue by Conkernel** [PacktPublishing/The-Kubernetes-Bible-Second-Edition#14]
Hi,

I'm looking for this second edition. I'd love to be the first to read it... but I'm not being able to find this second edition on the market. Any way to purchase it somewhere?

Thanks a lot!

**Comment by iamgini** [comment]
@Conkernel thank you so much for your interest in the 2nd edition.
The book will be published by Sep 2024 but you can pre-order your copy now: https://amzn.to/4dX3cqk

**Comment by Conkernel** [comment]
Hi iamgini, thanks for your answer. September will be too late for me to het the book, as I need to re-start learning again these days for the new job, and I've already read your first edition. Is there a way to access to a kind of draft of the second edition, as Manning does with their MEAP books?

Best regards

**Comment by iamgini** [comment]
Closing as no more updates.
